name: Monitor AI News

on:
  schedule:
    # Monday, Wednesday, Friday at 9 AM UTC
    - cron: '0 9 * * 1,3,5'
  
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
      
      - name: Monitor news feeds
        run: python scripts/monitor-news.py
      
      - name: Notify Discord (if updates found)
        if: failure() == false
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          echo "News monitoring complete - check logs for updates"
